name: Merge Dev to Main

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Name of the previous workflow
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all branches and history
        token: ${{ secrets.TOKEN }}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Merge Dev to Main
      run: |
        git checkout main
        git merge dev
        git push origin main