name: Merge to Main

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  merge_to_main:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Merge dev branch into main
      run: |
        git checkout main
        git merge dev
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
